version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: selfstorage
      POSTGRES_USER: selfuser
      POSTGRES_PASSWORD: selfpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - backend

volumes:
  postgres_data:
